### ISSUE TITLE
Gemfire sink fails to deploy

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/gemfire#3]
As a user, I'm using the gemfire-sink in an SCDF stream and the application fails to bootstrap with errors. This is on the local-server - 1.1.2.RELEASE. 

**stream:**
```
stream create --name gff1 --definition " file --directory=/gpdata/data/input | gfs1: gemfire --pool.connect-type='server' --pool.host-addresses='HOST:10334' --key-expression=payload.getField('vin').concat(payload.getField('key')) --region.region-name=TEST " --deploy
```

**error:**
```
2017-03-03 02:35:33.540 ERROR 2890 --- [ main] o.s.boot.SpringApplication : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gemfirePool' defined in org.springframework.cloud.stream.app.gemfire.config.GemfirePoolConfiguration: Bean instantiati
on via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.gemfire.client.PoolFactoryBean]: Factory method 'gemfi
rePool' threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.data.gemfire.client.PoolFactoryBean.setLocatorEndpointList(Lorg/springframework/data/gemfire/support/ConnectionE
ndpointList;)V
at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128) ~[spring-beans-4.3.3.RELEASE.jar!/:4.3.3.R
ELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1023) ~[spring-beans-4.3.3.RELEASE.jar!/:4.3.3.RELEASE]
```

**Comment by sabbyanandan** [comment]
Addressed via: https://github.com/spring-cloud-stream-app-starters/gemfire/pull/7
